### ISSUE TITLE
Support for Firefox?  Patch forthcoming.

### ISSUE THREAD

**Issue by jclark-dot-org** [dnakov/force-apiNames#10]
With the release of Firefox Quantum (57.0), I'm trying it out for the first time in years, and finding I can't live without a couple of key plugins (force-navigator is next!).  I'm hoping you'll release this as a Firefox addon.

[Mozilla provides instructions for porting a Chrome extension to Firefox][1], which I've been reviewing.  You'll need to handle the "Submit your add-on to AMO for signing and distribution" step, but I've been working through the other steps.  I've found one incompatibility:  [Firefox doesn't support relative urls in `fetch()` calls][2].  I've got a working fix that gets the current tab's url's origin and passes it into the contentscript, which prefixes all the `fetch()` call relative urls.  It's working for me in Firefox and in Chrome.  I'll submit a pull request shortly.

[1]: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
[2]: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Content_script_requests_happen_in_the_context_of_extension_not_content_page

**Comment by dnakov** [comment]
Fantastic! Wow, you can now just publish a .crx. Love it. I'll submit it.

**Comment by dnakov** [comment]
submitted under sfdc-api-fieldnames. waiting for review!
Thanks!

**Comment by jclark-dot-org** [comment]
It's live:  https://addons.mozilla.org/en-US/firefox/addon/sfdc-api-fieldnames/
